### ISSUE TITLE
Branches referenced in the requirements.txt do not exist.

### ISSUE THREAD

**Issue by lennarteingunia** [buoyancy99/ramp-rl#2]
The `requirements.txt` file references `https://github.com/buoyancy99/stable-baselines3@ramp-rl` as an existing branch. As far as I can tell this branch does not exist.
The same is true for `https://github.com/buoyancy99/metaworld@ramp-rl`.

**Comment by buoyancy99** [comment]
I am really sorry! I forgot to rename those branches to ramp-rl. Just fixed it

**Comment by buoyancy99** [comment]
Should have been resolved
